version: '3.7'
services:
  db:
    image: mysql:latest
    ports: 
    - "3306:3306"
    environment:       
      MYSQL_USER: crud
      MYSQL_DATABASE: crud_laravel
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Sao_Paulo        
  redis:
    image: redis:latest      
  dev:    
    build: 
      context: '.'        
      args:
        uid: ${UID}
    user: ${UID}
    ports:
    - "8000:8000"
    volumes:    
    - './laravel:/app'
    working_dir: /app
    links:
    - db
    - redis
    command: /bin/sh -c "composer install && npm install && npm run dev && php artisan migrate:fresh --seed && php artisan serve --host 0.0.0.0"
